version: '3.1'
services:
  db:
    container_name: mariadb-11.0.3-jammy
    image: mariadb:11.0.3-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
  adminer:
    container_name: adminer-4.8.1-standalone
    image: adminer:4.8.1-standalone
    restart: always
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the SMTP server should be accessible on
      - 9025:25
   
  